In [1]:
df=pd.read_csv("diabetes.csv")

<IPython.core.display.Javascript object>

In [2]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
df['Glucose']=np.where(df['Glucose']==0,df['Glucose'].median(),df['Glucose'])
df['Insulin']=np.where(df['Insulin']==0,df['Insulin'].median(),df['Insulin'])
df['SkinThickness']=np.where(df['SkinThickness']==0,df['SkinThickness'].median(),df['SkinThickness'])
df.head()

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6    148.0             72           35.0     30.5  33.6   
1            1     85.0             66           29.0     30.5  26.6   
2            8    183.0             64           23.0     30.5  23.3   
3            1     89.0             66           23.0     94.0  28.1   
4            0    137.0             40           35.0    168.0  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
x=df.iloc[:,:8]
y=df.iloc[:,-1]

In [5]:
x.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6    148.0             72           35.0     30.5  33.6   
1            1     85.0             66           29.0     30.5  26.6   
2            8    183.0             64           23.0     30.5  23.3   
3            1     89.0             66           23.0     94.0  28.1   
4            0    137.0             40           35.0    168.0  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [6]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=33)

In [8]:
from sklearn.ensemble import RandomForestClassifier
rf_classifier=RandomForestClassifier(n_estimators=10)
rf_classifier.fit(x_train,y_train)
y_pred=rf_classifier.predict(x_test)

In [9]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.7597402597402597
[[85 14]
 [23 32]]
              precision    recall  f1-score   support

           0       0.79      0.86      0.82        99
           1       0.70      0.58      0.63        55

    accuracy                           0.76       154
   macro avg       0.74      0.72      0.73       154
weighted avg       0.75      0.76      0.75       154



In [10]:
model=RandomForestClassifier(n_estimators=500,criterion='entropy',max_features='sqrt',min_samples_leaf=10,random_state=100)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.7467532467532467
[[88 11]
 [28 27]]
              precision    recall  f1-score   support

           0       0.76      0.89      0.82        99
           1       0.71      0.49      0.58        55

    accuracy                           0.75       154
   macro avg       0.73      0.69      0.70       154
weighted avg       0.74      0.75      0.73       154



In [11]:
[int(x) for x in np.linspace(start=200,stop=2000,num=10)]

<IPython.core.display.Javascript object>

[200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]

In [12]:
from sklearn.model_selection import RandomizedSearchCV
n_estimators=[int(x) for x in np.linspace(start=200,stop=2000,num=10)]
max_features=['auto','sqrt','log2']
max_depth=[int(x) for x in np.linspace(10,100,10)]
min_samples_split=[2,5,10,14]
min_samples_leaf=[1,2,4,6,8]
random_grid={'n_estimators':n_estimators,'max_features':max_features,'max_depth':max_depth,'min_samples_split':min_samples_split,'min_samples_leaf':min_samples_leaf,'criterion':['entropy','gini']}
print(random_grid)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100], 'min_samples_split': [2, 5, 10, 14], 'min_samples_leaf': [1, 2, 4, 6, 8], 'criterion': ['entropy', 'gini']}


In [13]:
    rf_Randomcv=RandomizedSearchCV(estimator=rf_classifier,param_distributions=random_grid,n_iter=100,cv=3,verbose=2,random_state=100,n_jobs=-1)
    rf_Randomcv.fit(x_train,y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:  4.3min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  8.5min finished


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(n_estimators=10),
                   n_iter=100, n_jobs=-1,
                   param_distributions={'criterion': ['entropy', 'gini'],
                                        'max_depth': [10, 20, 30, 40, 50, 60,
                                                      70, 80, 90, 100],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [1, 2, 4, 6, 8],
                                        'min_samples_split': [2, 5, 10, 14],
                                        'n_estimators': [200, 400, 600, 800,
                                                         1000, 1200, 1400, 1600,
                                                         1800, 2000]},
                   random_state=100, verbose=2)

In [22]:
rf_Randomcv.best_params_

{'n_estimators': 200,
 'min_samples_split': 14,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'max_depth': 10,
 'criterion': 'gini'}

In [45]:
from sklearn.model_selection import GridSearchCV

param_grid= {
    'criterion': [rf_Randomcv.best_params_['criterion']],
    'max_depth' :[rf_Randomcv.best_params_['max_depth']],
    'max_features': [rf_Randomcv.best_params_['max_features']],
    'min_samples_leaf': [rf_Randomcv.best_params_['min_samples_leaf'],
                        rf_Randomcv.best_params_['min_samples_leaf']+2,
                        rf_Randomcv.best_params_['min_samples_leaf']+4],
    'min_samples_split': [rf_Randomcv.best_params_['min_samples_split']-2,
                        rf_Randomcv.best_params_['min_samples_split']-1,
                        rf_Randomcv.best_params_['min_samples_split'],
                        rf_Randomcv.best_params_['min_samples_split']+1,
                        rf_Randomcv.best_params_['min_samples_split']+2],
    'n_estimators':[rf_Randomcv.best_params_['n_estimators']-150,
                    rf_Randomcv.best_params_['n_estimators']-100,
                    rf_Randomcv.best_params_['n_estimators'],
                    rf_Randomcv.best_params_['n_estimators']+100,
                    rf_Randomcv.best_params_['n_estimators']+200]
}
print(param_grid)

{'criterion': ['gini'], 'max_depth': [10], 'max_features': ['sqrt'], 'min_samples_leaf': [1, 3, 5], 'min_samples_split': [12, 13, 14, 15, 16], 'n_estimators': [50, 100, 200, 300, 400]}


In [46]:
                        [rf_Randomcv.best_params_['min_samples_split']-2,
                        rf_Randomcv.best_params_['min_samples_split']-1,
                        rf_Randomcv.best_params_['min_samples_split'],
                        rf_Randomcv.best_params_['min_samples_split']+1,
                        rf_Randomcv.best_params_['min_samples_split']+2]

[12, 13, 14, 15, 16]

In [47]:
rf=RandomForestClassifier()
grid_search=GridSearchCV(estimator=rf,param_grid=param_grid,cv=10,n_jobs=-1,verbose=2)
grid_search.fit(x_train,y_train)

Fitting 10 folds for each of 75 candidates, totalling 750 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:    6.6s
[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:   42.6s
[Parallel(n_jobs=-1)]: Done 357 tasks      | elapsed:  1.7min
[Parallel(n_jobs=-1)]: Done 640 tasks      | elapsed:  3.0min
[Parallel(n_jobs=-1)]: Done 750 out of 750 | elapsed:  3.6min finished


GridSearchCV(cv=10, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini'], 'max_depth': [10],
                         'max_features': ['sqrt'],
                         'min_samples_leaf': [1, 3, 5],
                         'min_samples_split': [12, 13, 14, 15, 16],
                         'n_estimators': [50, 100, 200, 300, 400]},
             verbose=2)

In [64]:
grid_search.best_estimator_

RandomForestClassifier(max_depth=10, max_features='sqrt', min_samples_leaf=5,
                       min_samples_split=15, n_estimators=400)

In [65]:
best_grid=grid_search.best_estimator_

In [66]:
y_pred=best_grid.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print('Accuracy Score {}'.format(accuracy_score(y_test,y_pred)))
print('Classificaton report: {}'.format(classification_report(y_test,y_pred)))

[[86 13]
 [26 29]]
Accuracy Score 0.7467532467532467
Classificaton report:               precision    recall  f1-score   support

           0       0.77      0.87      0.82        99
           1       0.69      0.53      0.60        55

    accuracy                           0.75       154
   macro avg       0.73      0.70      0.71       154
weighted avg       0.74      0.75      0.74       154



In [67]:
from hyperopt import hp,fmin,tpe,STATUS_OK,Trials

In [68]:
space= {'criterion': hp.choice('criterion',['entropy','gini']),
       'max_depth':hp.quniform('max_depth', 10,1200,10),
       'max_features':hp.choice('max_features',['auto','sqrt','log2',None]),
       'min_samples_leaf':hp.uniform('min_samples_leaf',0,0.5),
       'min_samples_split':hp.uniform('min_samples_split',0,1),
       'n_estimators':hp.choice('n_estimators',[10,50,300,750,1200,1300,1500])
       }


In [69]:
space

{'criterion': <hyperopt.pyll.base.Apply at 0xe624ca0>,
 'max_depth': <hyperopt.pyll.base.Apply at 0xe624790>,
 'max_features': <hyperopt.pyll.base.Apply at 0xe6245e0>,
 'min_samples_leaf': <hyperopt.pyll.base.Apply at 0xe639640>,
 'min_samples_split': <hyperopt.pyll.base.Apply at 0xe639880>,
 'n_estimators': <hyperopt.pyll.base.Apply at 0xe6398b0>}

In [70]:
from sklearn.model_selection import cross_val_score
def objective (space):
    model=RandomForestClassifier(criterion=space['criterion'],max_depth=space['max_depth'],max_features=space['max_features'],min_samples_leaf=space['min_samples_leaf'],min_samples_split=space['min_samples_split'],n_estimators = space['n_estimators'])
    accuracy=cross_val_score(model,x_train,y_train,cv=5).mean()
    return {'loss': -accuracy,'satus':STATUS_OK}

In [71]:
trials = Trials()
best = fmin(fn= objective,
            space= space,
            algo= tpe.suggest,
            max_evals = 80,
            trials= trials)


  0%|                                   | 0/80 [00:00<?, ?trial/s, best loss=?]

job exception: 'status'



  0%|                                   | 0/80 [00:20<?, ?trial/s, best loss=?]


KeyError: 'status'